# BP: Estimated Delivery & Geo — App Configuration
# Copyright © 2025 BluePeaks. All rights reserved.
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "137c0b77a4a89cbb8fb4d7670cc6849f"
name = "BP: Estimated Delivery & Geo"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Delivery app chỉ cần đọc thông tin cơ bản, không cần write_products
scopes = "read_orders,read_customers"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[app_proxy]
url = "https://shopify.dev/apps/default-app-home/api/delivery"
subpath = "bp-delivery"
prefix = "apps"
