ALTER TABLE "DeliveryRule"
ADD COLUMN "cutoffEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "cutoffTime" TEXT NOT NULL DEFAULT '17:00',
ADD COLUMN "cutoffTimezone" TEXT NOT NULL DEFAULT 'UTC',
ADD COLUMN "holidayDates" JSONB,
ADD COLUMN "visibilityMode" TEXT NOT NULL DEFAULT 'visible',
ADD COLUMN "timerSeconds" INTEGER NOT NULL DEFAULT 8100,
ADD COLUMN "dateLocale" TEXT NOT NULL DEFAULT 'en-AU';
